/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Libro;
import controlador.controlLibro;
import java.awt.Image;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

n
/**
 *
 * @author luise
 */
public class ActualizarLibro extends javax.swing.JFrame {
    private controlLibro control;
    private Libro libro;
    private Map<Integer, String> categorias;
    private Map<Integer, String> estanterias;
    

     private void CargarLogo(){
n        
        ImageIcon ico = new ImageIcon(getClass().getResource("/archivos/Vizcalla.png"));
        Image im = ico.getImage().getScaledInstance(lbl_libros.getWidth(),lbl_libros.getHeight(), Image.SCALE_SMOOTH);
        lbl_libros.setIcon(new ImageIcon(im));
        
        ImageIcon icw = new ImageIcon(getClass().getResource("/archivos/Lapiz.png"));
        Image iw = icw.getImage().getScaledInstance(lbl_lapiz.getWidth(),lbl_lapiz.getHeight(), Image.SCALE_SMOOTH);
        lbl_lapiz.setIcon(new ImageIcon(iw));
        
        ImageIcon icn = new ImageIcon(getClass().getResource("/archivos/luis4.png"));
        Image in = icn.getImage().getScaledInstance(lbl_curva.getWidth(),lbl_curva.getHeight(), Image.SCALE_SMOOTH);
        lbl_curva.setIcon(new ImageIcon(in));
    }
    public ActualizarLibro(controlLibro control, Libro libro) {
        initComponents(); // inicializa los textfields y combobox
        this.control = control;
        this.libro = libro;
        CargarLogo();
        
        categorias = control.listarCategoriasMap();
        estanterias = control.listarEstanteriasMap();
        
        for (String nombre : categorias.values()) {
            comboCategoria.addItem(nombre);
        }
        comboCategoria.setSelectedItem(categorias.get(libro.getCategoria_id()));

        for (String codigo : estanterias.values()) {
            comboEstanteria.addItem(codigo);
        }
        comboEstanteria.setSelectedItem(estanterias.get(libro.getEstante_id()));
        
        /*
        for(String cat : control.listarCategorias()){
            comboCategoria.addItem(cat);
        }
        for(String est : control.listarEstanterias()){
            comboEstanteria.addItem(est);
        }*/
        
        // Cargar datos en los campos
        txtTitulo.setText(libro.getTitulo());
        txtAutor.setText(libro.getAutor());
        txtEditorial.setText(libro.getEditorial());
        txtCopias.setText(String.valueOf(libro.getN_copias()));
        txtFecha.setText(libro.getFecha_publicacion().toString());
        txtTomo.setText(libro.getTomo());
        txtIsbn.setText(libro.getIsbn());
        txtFila.setText(String.valueOf(libro.getFila()));
        txtEdicion.setText(libro.getEdicion());
        /*
        // Seleccionar el ID correcto del libro
        Map<Integer, String> categorias = control.listarCategoriasMap();
        for (String nombre : categorias.values()) {
            comboCategoria.addItem(nombre);
        }
        comboCategoria.setSelectedItem(categorias.get(libro.getCategoria_id()));

        Map<Integer, String> estanterias = control.listarEstanteriasMap();
        for (String codigo : estanterias.values()) {
            comboEstanteria.addItem(codigo);
        }
        comboEstanteria.setSelectedItem(estanterias.get(libro.getEstante_id()));*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

n        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboEstanteria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFila = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtTomo = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCopias = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        lbl_libros = new javax.swing.JLabel();
        lbl_lapiz = new javax.swing.JLabel();
        lbl_curva = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Actualizar Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Numero de copias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 130, 37));
        jLabel3.setText("Titulo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 130, 37));
        jLabel4.setText("ISBN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        comboEstanteria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboEstanteria.setForeground(new java.awt.Color(0, 113, 114));
        comboEstanteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTANTERIA", " " }));
        jPanel1.add(comboEstanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 320, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 130, 37));
        jLabel6.setText("Autor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 130, 37));
        jLabel8.setText("Fila");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

... (file continues)
