package Vista;

import DAO.CategoriaDAO;
import Modelo.Categorias;
import Modelo.Libro;
import controlador.conexionSQL;
import controlador.controlLibro;
import java.awt.Image;
import java.sql.Connection;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luise
 */
public class Consultas extends javax.swing.JFrame {
    private Connection con;
    
    public Consultas() {
        initComponents();
        con = conexionSQL.getConnection();
        cargarCategorias();
        CargarLogo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

n        jPanel1 = new javax.swing.JPanel();
        lbl_consulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        combo_categorias = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        lbl_libros = new javax.swing.JLabel();
        lbl_lupa = new javax.swing.JLabel();
        lbl_curva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_consulta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_consulta.setForeground(new java.awt.Color(242, 130, 37));
        lbl_consulta.setText("Consulta Libros");
        jPanel1.add(lbl_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 15, -1, -1));

... (file continues)
