/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Vista_copia;

import Modelo.Libro;
import controlador.controlLibro;
import java.awt.Image;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author luise
 */
public class ActualizarLibro extends javax.swing.JFrame {
    private controlLibro control;
    private Libro libro;
    private Map<Integer, String> categorias;
    private Map<Integer, String> estanterias;
    

     private void CargarLogo(){
        
        ImageIcon ico = new ImageIcon(getClass().getResource("/archivos/Vizcalla.png"));
        Image im = ico.getImage().getScaledInstance(lbl_libros.getWidth(),lbl_libros.getHeight(), Image.SCALE_SMOOTH);
        lbl_libros.setIcon(new ImageIcon(im));
        
        ImageIcon icw = new ImageIcon(getClass().getResource("/archivos/Lapiz.png"));
        Image iw = icw.getImage().getScaledInstance(lbl_lapiz.getWidth(),lbl_lapiz.getHeight(), Image.SCALE_SMOOTH);
        lbl_lapiz.setIcon(new ImageIcon(iw));
        
        ImageIcon icn = new ImageIcon(getClass().getResource("/archivos/luis4.png"));
        Image in = icn.getImage().getScaledInstance(lbl_curva.getWidth(),lbl_curva.getHeight(), Image.SCALE_SMOOTH);
        lbl_curva.setIcon(new ImageIcon(in));
    }
    public ActualizarLibro(controlLibro control, Libro libro) {
        initComponents(); // inicializa los textfields y combobox
        this.control = control;
        this.libro = libro;
        CargarLogo();
        
        categorias = control.listarCategoriasMap();
        estanterias = control.listarEstanteriasMap();
        
        for (String nombre : categorias.values()) {
            comboCategoria.addItem(nombre);
        }
        comboCategoria.setSelectedItem(categorias.get(libro.getCategoria_id()));

        for (String codigo : estanterias.values()) {
            comboEstanteria.addItem(codigo);
        }
        comboEstanteria.setSelectedItem(estanterias.get(libro.getEstante_id()));
        
        /*
        for(String cat : control.listarCategorias()){
            comboCategoria.addItem(cat);
        }
        for(String est : control.listarEstanterias()){
            comboEstanteria.addItem(est);
        }*/
        
        // Cargar datos en los campos
        txtTitulo.setText(libro.getTitulo());
        txtAutor.setText(libro.getAutor());
        txtEditorial.setText(libro.getEditorial());
        txtCopias.setText(String.valueOf(libro.getN_copias()));
        txtFecha.setText(libro.getFecha_publicacion().toString());
        txtTomo.setText(libro.getTomo());
        txtIsbn.setText(libro.getIsbn());
        txtFila.setText(String.valueOf(libro.getFila()));
        txtEdicion.setText(libro.getEdicion());
        /*
        // Seleccionar el ID correcto del libro
        Map<Integer, String> categorias = control.listarCategoriasMap();
        for (String nombre : categorias.values()) {
            comboCategoria.addItem(nombre);
        }
        comboCategoria.setSelectedItem(categorias.get(libro.getCategoria_id()));

        Map<Integer, String> estanterias = control.listarEstanteriasMap();
        for (String codigo : estanterias.values()) {
            comboEstanteria.addItem(codigo);
        }
        comboEstanteria.setSelectedItem(estanterias.get(libro.getEstante_id()));*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboEstanteria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFila = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtTomo = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCopias = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        lbl_libros = new javax.swing.JLabel();
        lbl_lapiz = new javax.swing.JLabel();
        lbl_curva = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Actualizar Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Numero de copias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 130, 37));
        jLabel3.setText("Titulo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 130, 37));
        jLabel4.setText("ISBN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        comboEstanteria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboEstanteria.setForeground(new java.awt.Color(0, 113, 114));
        comboEstanteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTANTERIA", " " }));
        jPanel1.add(comboEstanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 320, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 130, 37));
        jLabel6.setText("Autor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 130, 37));
        jLabel8.setText("Fila");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 130, 37));
        jLabel9.setText("Fecha de publicacion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 130, 37));
        jLabel10.setText("Tomo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 130, 37));
        jLabel11.setText("Editorial");
        jLabel11.setMaximumSize(new java.awt.Dimension(67, 32));
        jLabel11.setMinimumSize(new java.awt.Dimension(67, 32));
        jLabel11.setPreferredSize(new java.awt.Dimension(67, 32));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 20));

        btn_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(0, 113, 114));
        btn_actualizar.setText("Guardar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 130, 37));
        jLabel5.setText("Edicion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        txtFila.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 320, -1));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 320, -1));

        txtEditorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 320, -1));

        txtIsbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 320, -1));

        txtTomo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 320, -1));

        txtEdicion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicionActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 320, -1));

        txtAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 320, -1));

        txtCopias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 320, -1));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 320, -1));

        comboCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboCategoria.setForeground(new java.awt.Color(0, 113, 114));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIAS", " " }));
        jPanel1.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 320, 40));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 260, -1));

        lbl_libros.setText("jLabel7");
        jPanel1.add(lbl_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 590, 510));

        lbl_lapiz.setText("jLabel7");
        jPanel1.add(lbl_lapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 320, 310));

        lbl_curva.setText("jLabel7");
        jPanel1.add(lbl_curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1120, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // Actualizar los datos del objeto libro con lo que el usuario editó
        libro.setTitulo(txtTitulo.getText());
        libro.setAutor(txtAutor.getText());
        libro.setEditorial(txtEditorial.getText());
        libro.setN_copias(Integer.parseInt(txtCopias.getText()));
        libro.setFecha_publicacion(java.sql.Date.valueOf(txtFecha.getText())); // formato yyyy-MM-dd
        libro.setTomo(txtTomo.getText());
        libro.setIsbn(txtIsbn.getText());
        libro.setFila(Integer.parseInt(txtFila.getText()));
        libro.setEdicion(txtEdicion.getText());

        // Obtener el nombre/código seleccionado
        String categoriaNombre = comboCategoria.getSelectedItem().toString();
        String estanteriaCodigo = comboEstanteria.getSelectedItem().toString();
        
        // Buscar el ID correspondiente en el Map
        int categoriaId = categorias.entrySet()
            .stream()
            .filter(e -> e.getValue().equals(categoriaNombre))
            .map(Map.Entry::getKey)
            .findFirst()
            .orElse(0);

        int estanteriaId = estanterias.entrySet()
            .stream()
            .filter(e -> e.getValue().equals(estanteriaCodigo))
            .map(Map.Entry::getKey)
            .findFirst()
            .orElse(0);

    libro.setCategoria_id(categoriaId);
    libro.setEstante_id(estanteriaId);

        // Llamar al control para actualizar
        int resultado = control.actualizarLibro(libro);

        if(resultado == 1){
            JOptionPane.showMessageDialog(this, "Libro actualizado correctamente");
            this.dispose(); // cerrar ventana
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el libro", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txtEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicionActionPerformed
/*public ActualizarLibro() {
    initComponents(); // inicializa los textfields y combobox
}*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ActualizarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboEstanteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_curva;
    private javax.swing.JLabel lbl_lapiz;
    private javax.swing.JLabel lbl_libros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCopias;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFila;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTomo;
    // End of variables declaration//GEN-END:variables
}
