/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Libro;
import controlador.controlLibro;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author luise
 */
public class ActualizarLibro extends javax.swing.JFrame {
    private controlLibro control;
    private Libro libro;
    private Map<Integer, String> categorias;
    private Map<Integer, String> estanterias;
    // estado previo de búsqueda para restaurar al volver
    private String prevSearchTitle = null;
    private int prevSearchCategoryId = -1;

    public ActualizarLibro(controlLibro control, Libro libro) {
        initComponents(); // inicializa los textfields y combobox
        // Cargar elementos gráficos (imágenes decorativas)
        CargarLogo();
        // Bind Escape key to call the same handler as the Volver button.
        // The NetBeans-generated code declares the button as a local variable inside initComponents(),
        // so we invoke the existing action method directly instead of calling doClick() on the button instance.
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "volver");
        getRootPane().getActionMap().put("volver", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Reuse the generated action handler so behavior stays in one place
                btn_VolverActionPerformed(new ActionEvent(ActualizarLibro.this, ActionEvent.ACTION_PERFORMED, "escape"));
            }
        });
        this.control = control;
        this.libro = libro;
        
        categorias = control.listarCategoriasMap();
        estanterias = control.listarEstanteriasMap();
        
        for (String nombre : categorias.values()) {
            comboCategoria.addItem(nombre);
        }
        comboCategoria.setSelectedItem(categorias.get(libro.getCategoria_id()));

        for (String codigo : estanterias.values()) {
            comboEstanteria.addItem(codigo);
        }
        comboEstanteria.setSelectedItem(estanterias.get(libro.getEstante_id()));
        
        /*
        for(String cat : control.listarCategorias()){
            comboCategoria.addItem(cat);
        }
        for(String est : control.listarEstanterias()){
            comboEstanteria.addItem(est);
        }*/
        
        // Cargar datos en los campos
        txtTitulo.setText(libro.getTitulo());
        txtAutor.setText(libro.getAutor());
        txtEditorial.setText(libro.getEditorial());
        txtCopias.setText(String.valueOf(libro.getN_copias()));
        jDateChooser1.setDate(libro.getFecha_publicacion());
        txtTomo.setText(libro.getTomo());
        txtIsbn.setText(libro.getIsbn());
        txtFila.setText(String.valueOf(libro.getFila()));
        txtEdicion.setText(libro.getEdicion());
        /*
        // Seleccionar el ID correcto del libro
        Map<Integer, String> categorias = control.listarCategoriasMap();
        for (String nombre : categorias.values()) {
            comboCategoria.addItem(nombre);
        }
        comboCategoria.setSelectedItem(categorias.get(libro.getCategoria_id()));

        Map<Integer, String> estanterias = control.listarEstanteriasMap();
        for (String codigo : estanterias.values()) {
            comboEstanteria.addItem(codigo);
        }
        comboEstanteria.setSelectedItem(estanterias.get(libro.getEstante_id()));*/

    }

    /**
     * Nueva sobrecarga que recibe el estado previo de búsqueda (texto y categoría)
     */
    public ActualizarLibro(controlLibro control, Libro libro, String prevTitle, int prevCategoryId) {
        this(control, libro);
        this.prevSearchTitle = prevTitle;
        this.prevSearchCategoryId = prevCategoryId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboEstanteria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        javax.swing.JButton btn_Volver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFila = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtTomo = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCopias = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        lbl_libros = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbl_lapiz = new javax.swing.JLabel();
        lbl_curva = new javax.swing.JLabel();
        lbl_titulo2 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setForeground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Actualizar Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 450, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Numero de copias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 240, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 130, 37));
        jLabel3.setText("Titulo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 110, 60));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 130, 37));
        jLabel4.setText("ISBN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 60));

        comboEstanteria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboEstanteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTANTERIA", " " }));
        jPanel1.add(comboEstanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 460, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 130, 37));
        jLabel6.setText("Autor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 90, 50));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 130, 37));
        jLabel8.setText("Fila");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 110, 50));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 130, 37));
        jLabel9.setText("Fecha de publicacion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 290, 40));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 130, 37));
        jLabel10.setText("Tomo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 110, 50));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 130, 37));
        jLabel11.setText("Editorial");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 50));

        btn_actualizar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(0, 113, 114));
        btn_actualizar.setText("Guardar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 260, 50));

        btn_Volver.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_Volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_Volver.setText("Volver");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 280, 50));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 130, 37));
        jLabel5.setText("Edicion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 120, 40));

        txtFila.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 460, 30));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 460, 30));

        txtEditorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 460, 30));

        txtIsbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 460, 30));

        txtTomo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 460, 30));

        txtEdicion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 460, 30));

        txtAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 460, 30));

        txtCopias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 460, 30));

        comboCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIAS", " " }));
        jPanel1.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 460, 40));

        lbl_libros.setText("jLabel7");
        jPanel1.add(lbl_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, 330, 260));

        jDateChooser1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 460, 30));

        lbl_lapiz.setText("jLabel7");
        jPanel1.add(lbl_lapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 200, 220));

        lbl_curva.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_curva.setText("jLabel7");
        jPanel1.add(lbl_curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1360, 300));

        lbl_titulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titulo2.setForeground(new java.awt.Color(242, 130, 37));
        lbl_titulo2.setText("Categoria");
        jPanel1.add(lbl_titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(242, 130, 37));
        lbl_titulo.setText("Estanteria");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // Actualizar los datos del objeto libro con lo que el usuario editó
        libro.setTitulo(txtTitulo.getText());
        libro.setAutor(txtAutor.getText());
        libro.setEditorial(txtEditorial.getText());
        libro.setN_copias(Integer.parseInt(txtCopias.getText()));
        java.util.Date fecha = jDateChooser1.getDate();
            java.sql.Date fechaSQL = null;
            if (fecha != null) {
                fechaSQL = new java.sql.Date(fecha.getTime());
                libro.setFecha_publicacion(fechaSQL); // formato yyyy-MM-dd
            }        
        libro.setTomo(txtTomo.getText());
        libro.setIsbn(txtIsbn.getText());
        libro.setFila(Integer.parseInt(txtFila.getText()));
        libro.setEdicion(txtEdicion.getText());

        // Obtener el nombre/código seleccionado
        String categoriaNombre = comboCategoria.getSelectedItem().toString();
        String estanteriaCodigo = comboEstanteria.getSelectedItem().toString();
        
        // Buscar el ID correspondiente en el Map
        int categoriaId = categorias.entrySet()
            .stream()
            .filter(e -> e.getValue().equals(categoriaNombre))
            .map(Map.Entry::getKey)
            .findFirst()
            .orElse(0);

        int estanteriaId = estanterias.entrySet()
            .stream()
            .filter(e -> e.getValue().equals(estanteriaCodigo))
            .map(Map.Entry::getKey)
            .findFirst()
            .orElse(0);

    libro.setCategoria_id(categoriaId);
    libro.setEstante_id(estanteriaId);

        // Llamar al control para actualizar
        int resultado = control.actualizarLibro(libro);

        if(resultado == 1){
            JOptionPane.showMessageDialog(this, "Libro actualizado correctamente");
            // volver a la pantalla BuscarLibroActualizar restaurando el estado previo si existe
            BuscarLibroActualizar buscar;
            if (prevSearchTitle != null || prevSearchCategoryId > 0) {
                buscar = new BuscarLibroActualizar(prevSearchTitle, prevSearchCategoryId);
            } else {
                buscar = new BuscarLibroActualizar();
            }
            buscar.setLocationRelativeTo(null);
            buscar.setVisible(true);
            this.dispose(); // cerrar ventana
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el libro", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        // volver a la pantalla BuscarLibroActualizar restaurando estado previo si lo tenemos
        BuscarLibroActualizar buscar;
        if (prevSearchTitle != null || prevSearchCategoryId > 0) {
            buscar = new BuscarLibroActualizar(prevSearchTitle, prevSearchCategoryId);
        } else {
            buscar = new BuscarLibroActualizar();
        }
        buscar.setLocationRelativeTo(null);
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_VolverActionPerformed


    private void CargarLogo() {

        try {
            lbl_curva.setIcon(ImageHelper.getScaledIcon("/archivos/luis4.png", lbl_curva.getWidth(), lbl_curva.getHeight()));
            lbl_libros.setIcon(ImageHelper.getScaledIcon("/archivos/Vizcalla.png", lbl_libros.getWidth(), lbl_libros.getHeight()));
            lbl_lapiz.setIcon(ImageHelper.getScaledIcon("/archivos/Lapiz.png", lbl_lapiz.getWidth(), lbl_lapiz.getHeight()));
        } catch (Exception e) {
            // No queremos interrumpir la lógica si falla la carga de recursos
            System.err.println("Aviso: no se pudieron cargar las imágenes decorativas: " + e.getMessage());
        }
    }

    /**
     * Pone los campos en modo sólo lectura/bloqueado cuando se requiere.
     */
    
/*public ActualizarLibro() {
    initComponents(); // inicializa los textfields y combobox
}*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ActualizarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboEstanteria;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_curva;
    private javax.swing.JLabel lbl_lapiz;
    private javax.swing.JLabel lbl_libros;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo2;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCopias;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFila;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTomo;
    // End of variables declaration//GEN-END:variables
}
