/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import controlador.conexionSQL;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Modelo.Libro;




/**
 *
 * @author luise
 */
public class AgregarLibro extends javax.swing.JFrame {
    private Connection con;
    
    
  
    public AgregarLibro() {
        initComponents();
        // dateChooser will be created in initComponents so it is editable from NetBeans designer
        // load image icon into lbl_libro (same as Consultas)
        CargarLogo();
       
        
  
        try {
            con = conexionSQL.getConnection();
        
            DefaultComboBoxModel<String> modeloCategorias = new DefaultComboBoxModel<>();
            Statement stCat = con.createStatement();
            ResultSet rsCat = stCat.executeQuery("SELECT nombre FROM categorias");
            while (rsCat.next()) {
                modeloCategorias.addElement(rsCat.getString("nombre"));
            }
            jComboBoxCategorias.setModel(modeloCategorias);
            rsCat.close();
            stCat.close();
            
            DefaultComboBoxModel<String> modeloEstanterias = new DefaultComboBoxModel<>();
            Statement stEst = con.createStatement();
            ResultSet rsEst = stEst.executeQuery("SELECT codigo FROM estanterias");
            while (rsEst.next()) {
                modeloEstanterias.addElement(rsEst.getString("codigo"));
            }
            jComboBoxEstanterias.setModel(modeloEstanterias);
            rsEst.close();
            stEst.close();
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar combos: " + e.getMessage());
        }    
        
        
        
        
      
        
      
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEstanterias = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Btn_guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        box_fila = new javax.swing.JTextField();
        box_titulo = new javax.swing.JTextField();
        box_editorial = new javax.swing.JTextField();
        box_isbn = new javax.swing.JTextField();
        box_tomo = new javax.swing.JTextField();
        box_edicion = new javax.swing.JTextField();
        box_autor = new javax.swing.JTextField();
        box_copias = new javax.swing.JTextField();
        jComboBoxCategorias = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        box_codigo = new javax.swing.JTextField();
        box_posicion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FECHA = new com.toedter.calendar.JDateChooser();
        lbl_libro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 720));

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setForeground(new java.awt.Color(244, 226, 222));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Agregar Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Numero de copias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, 30));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(242, 130, 37));
        lbl_titulo.setText("Titulo");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 130, 37));
        jLabel4.setText("ISBN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jComboBoxEstanterias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxEstanterias.setForeground(new java.awt.Color(0, 113, 114));
        jComboBoxEstanterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTANTERIA", " " }));
        jPanel1.add(jComboBoxEstanterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 420, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 130, 37));
        jLabel6.setText("Autor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 130, 37));
        jLabel8.setText("Fila");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 130, 37));
        jLabel9.setText("Fecha de publicacion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 130, 37));
        jLabel10.setText("Tomo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 130, 37));
        jLabel11.setText("Editorial");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));

        Btn_guardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn_guardar.setText("Guardar");
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 260, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 130, 37));
        jLabel5.setText("Edicion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        box_fila.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        box_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_filaActionPerformed(evt);
            }
        });
        jPanel1.add(box_fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 320, -1));

        box_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        box_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_tituloActionPerformed(evt);
            }
        });
        jPanel1.add(box_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 320, -1));

        box_editorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(box_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 320, -1));

        box_isbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(box_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 320, -1));

        box_tomo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(box_tomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 320, -1));

        box_edicion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(box_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 320, -1));

        box_autor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        box_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_autorActionPerformed(evt);
            }
        });
        jPanel1.add(box_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 320, -1));

        box_copias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(box_copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 320, -1));

        jComboBoxCategorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxCategorias.setForeground(new java.awt.Color(0, 113, 114));
        jComboBoxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIAS", " " }));
        jPanel1.add(jComboBoxCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 420, 40));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 260, 40));

        box_codigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        box_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_codigoActionPerformed(evt);
            }
        });
        jPanel1.add(box_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 320, -1));

        box_posicion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(box_posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 130, 37));
        jLabel7.setText("Codigo ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 120, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 130, 37));
        jLabel12.setText("Posicion");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        FECHA.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 320, 30));
        jPanel1.add(lbl_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 450, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BORRAR ESTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btn_volverActionPerformed

    public class ItemCombo {
    private int id;
    private String nombre;

    public ItemCombo(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public int getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    // Esto hace que el combo muestre el nombre
    @Override
    public String toString() {
        return nombre;
    }
}

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try {
            con = conexionSQL.getConnection();
            String titulo = box_titulo.getText();
            String autor = box_autor.getText();
            String editorial = box_editorial.getText();
            String isbn = box_isbn.getText();
            String tomo = box_tomo.getText();
            String copias = box_copias.getText();
            
            // Pedazo de codigo: obtener fecha desde el JDateChooser
            java.util.Date fecha = FECHA.getDate();
            java.sql.Date fechaSQL = null;
            if (fecha != null) {
                fechaSQL = new java.sql.Date(fecha.getTime());
            }

            String fila = box_fila.getText();
            String edicion = box_edicion.getText();
            String categoria = (String) jComboBoxCategorias.getSelectedItem();
            String estanteria = (String) jComboBoxEstanterias.getSelectedItem();
            String codIdentificador = box_codigo.getText();
            String posicion =box_posicion.getText();

            int categoriaId = -1;
            PreparedStatement psCat = con.prepareStatement("SELECT id FROM categorias WHERE nombre = ?");
            psCat.setString(1, categoria);
            ResultSet rsCat = psCat.executeQuery();
            if (rsCat.next()) {
                categoriaId = rsCat.getInt("id");
            }
            rsCat.close();
            psCat.close();
            
            int estanteriaId = -1;
            PreparedStatement psEst = con.prepareStatement("SELECT id FROM estanterias WHERE codigo = ?");
            psEst.setString(1, estanteria);
            ResultSet rsEst = psEst.executeQuery();
            if (rsEst.next()) {
                estanteriaId = rsEst.getInt("id");
            }
            rsEst.close();
            psEst.close();
            
            
            String sql = "INSERT INTO libros (cod_identificador,titulo, autor, categoria_id, isbn, n_copias, estante_id,  fila, posicion, fecha_publicacion, editorial, tomo, edicion) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, codIdentificador);
            ps.setString(2, titulo);
            ps.setString(3, autor);
            ps.setInt(4, categoriaId);
            ps.setString(5, isbn);
            ps.setString(6, copias);
            ps.setInt(7, estanteriaId);
            ps.setString(8, fila);
            ps.setString(9, posicion);
            ps.setDate(10, fechaSQL);
            ps.setString(11, editorial);
            ps.setString(12, tomo);
            ps.setString(13, edicion);
            
            
            int filasAfectadas = ps.executeUpdate();
            if (filasAfectadas > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Libro guardado correctamente.");
            } else {    
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo guardar el libro.");
            }
            ps.close();
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar libro: " + e.getMessage());
        } finally {
            try {
                if (con != null) con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_Btn_guardarActionPerformed

    private void box_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_filaActionPerformed

    private void box_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_codigoActionPerformed

    private void box_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_tituloActionPerformed

    private void box_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_autorActionPerformed

    private void CargarLogo(){
        // match the behavior in Consultas: scale the image to the label size
        lbl_libro.setIcon(ImageHelper.getScaledIcon("/archivos/Vizcalla3.png", lbl_libro.getWidth(), lbl_libro.getHeight()));
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_guardar;
    private com.toedter.calendar.JDateChooser FECHA;
    private javax.swing.JTextField box_autor;
    private javax.swing.JTextField box_codigo;
    private javax.swing.JTextField box_copias;
    private javax.swing.JTextField box_edicion;
    private javax.swing.JTextField box_editorial;
    private javax.swing.JTextField box_fila;
    private javax.swing.JTextField box_isbn;
    private javax.swing.JTextField box_posicion;
    private javax.swing.JTextField box_titulo;
    private javax.swing.JTextField box_tomo;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> jComboBoxCategorias;
    private javax.swing.JComboBox<String> jComboBoxEstanterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_libro;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
