/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import controlador.conexionSQL;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Modelo.Libro;


/**
 *
 * @author DELL
 */
public class AgregarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AgregarUsuario
     */
    public AgregarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        jComboBoxEstanterias = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LblApellido = new javax.swing.JLabel();
        Btn_guardar = new javax.swing.JButton();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfCedula = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        jtfContraseña = new javax.swing.JTextField();
        btn_volver = new javax.swing.JButton();
        lbl_libro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(244, 226, 222));
        jPanel5.setForeground(new java.awt.Color(244, 226, 222));
        jPanel5.setMinimumSize(new java.awt.Dimension(1190, 700));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 130, 37));
        jLabel5.setText("Agregar Usuario");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 130, 37));
        jLabel6.setText("Contraseña");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, 30));

        lbl_Nombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(242, 130, 37));
        lbl_Nombre.setText("Nombre");
        jPanel5.add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(242, 130, 37));
        lblCedula.setText("Cedula");
        jPanel5.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jComboBoxEstanterias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxEstanterias.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxEstanterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Normal" }));
        jPanel5.add(jComboBoxEstanterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 220, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 130, 37));
        jLabel8.setText("Usuario");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 130, 37));
        jLabel10.setText("Permisos");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, -1, 30));

        LblApellido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblApellido.setForeground(new java.awt.Color(242, 130, 37));
        LblApellido.setText("Apellido");
        jPanel5.add(LblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));

        Btn_guardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn_guardar.setText("Guardar");
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });
        jPanel5.add(Btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 260, 40));

        jtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jPanel5.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 320, -1));

        jtfApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 320, -1));

        jtfCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtfCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 320, -1));

        jtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel5.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 320, -1));

        jtfContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 320, -1));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel5.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 260, 40));
        jPanel5.add(lbl_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 450, 430));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
        // TODO add your handling code here:
                                               
    String nombre = jtfNombre.getText();
    String apellido = jtfApellido.getText();
    String cedula = jtfCedula.getText();
    String usuario = jtfUsuario.getText();
    String password = jtfContraseña.getText();
    String permiso = jComboBoxEstanterias.getSelectedItem().toString();

    // Convertir permisos a 0 o 1
    int isAdmin = permiso.equalsIgnoreCase("Administrador") ? 1 : 0;

    // rol_id toma el mismo valor que is_admin
    int rol_id = 1;

    // Validación básica
    if (nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty() ||
        usuario.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Completa todos los campos");
        return;
    }

    Connection con = null;

    try {
        con = conexionSQL.getConnection();

        // Obtener el siguiente ID
        int nuevoID = 1;
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT MAX(id) AS max_id FROM usuarios");

        if (rs.next()) {
            nuevoID = rs.getInt("max_id") + 1;
        }

        rs.close();
        st.close();

        // Insertar usuario respetando el orden de la tabla
        String sql = "INSERT INTO usuarios (id, nombre, apellido, cedula, usuario, password, rol_id, is_admin) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, nuevoID);
        ps.setString(2, nombre);
        ps.setString(3, apellido);
        ps.setString(4, cedula);
        ps.setString(5, usuario);
        ps.setString(6, password);
        ps.setInt(7, rol_id);
        ps.setInt(8, isAdmin);

        ps.executeUpdate();
        ps.close();
        con.close();

        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar usuario: " + e.getMessage());
    }


        
    }//GEN-LAST:event_Btn_guardarActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:

        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> jComboBoxEstanterias;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCedula;
    private javax.swing.JTextField jtfContraseña;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_libro;
    // End of variables declaration//GEN-END:variables
}
