/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import controlador.conexionSQL;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
/**
 *
 * @author jq523
 */
public class Agregar_estanteria extends javax.swing.JFrame {
    private Connection con;

   
    public Agregar_estanteria() {
        initComponents();
        box_nombre.addActionListener(evt -> btn_guardar.doClick());
        
        // Bind Escape key to call the same handler as the Volver button.
        // The NetBeans-generated code declares the button as a local variable inside initComponents(),
        // so we invoke the existing action method directly instead of calling doClick() on the button instance.
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "volver");
        getRootPane().getActionMap().put("volver", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Reuse the generated action handler so behavior stays in one place
                btn_volverActionPerformed(new ActionEvent(Agregar_estanteria.this, ActionEvent.ACTION_PERFORMED, "escape"));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        box_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        numero_filas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 130, 37));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Agregar estanteria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 25, -1, -1));

        box_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(box_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 134, 185, -1));

        btn_guardar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 113, 114));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 40));

        btn_volver.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 160, 40));

        numero_filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_filasActionPerformed(evt);
            }
        });
        jPanel1.add(numero_filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 226, 185, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Numero de filas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 188, 185, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 130, 37));
        jLabel3.setText("Letra estanteria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 96, 185, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_nombreActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
 
      String codigoEstanteria = box_nombre.getText().trim();
    String filasTexto = numero_filas.getText().trim();

    // Validar que sea UNA sola letra
    if (codigoEstanteria.isEmpty() || codigoEstanteria.length() != 1 || !Character.isLetter(codigoEstanteria.charAt(0))) {
        JOptionPane.showMessageDialog(this, 
            "La estantería debe ser una sola letra (A-Z)", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar número de filas
    int nFilas;
    try {
        nFilas = Integer.parseInt(filasTexto);
        if (nFilas <= 0) {
            JOptionPane.showMessageDialog(this, 
                "El número de filas debe ser mayor que 0", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Ingrese un número válido para las filas", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Conectar a la base de datos
    con = conexionSQL.getConnection();

    String sql = "INSERT INTO estanterias (codigo, n_filas) VALUES (?, ?)";

    try {
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, codigoEstanteria.toUpperCase()); // Guardar en mayúscula
        pst.setInt(2, nFilas);

        int filas = pst.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, 
                "Estantería guardada exitosamente", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            box_nombre.setText("");
            numero_filas.setText("");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error al guardar la estantería: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }

    }
    {
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
     
        // Abrir la ventana del menú principal
        MenuPrincipal menu = new MenuPrincipal(); // asegúrate de que exista esta clase
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();
        
    }//GEN-LAST:event_btn_volverActionPerformed

    private void numero_filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_filasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_filasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_estanteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_estanteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_estanteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_estanteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_estanteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_nombre;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numero_filas;
    // End of variables declaration//GEN-END:variables

}