/*
 * Simple Ajustes window with a button to generate a SQL backup using mysqldump.
*/
package Vista;

import controlador.conexionSQL;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.ResultSetMetaData;
import java.sql.DatabaseMetaData;
import java.sql.Statement;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;

public class Ajustes extends javax.swing.JFrame {

    public Ajustes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                           
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        btnRespaldo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
    jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajustes - Respaldo");
        setMinimumSize(new java.awt.Dimension(420, 180));
        setPreferredSize(new java.awt.Dimension(420, 180));

        jPanel1.setLayout(null);

        lblInfo.setText("Haga clic en 'Generar respaldo' para exportar la base de datos a un archivo .sql");
        jPanel1.add(lblInfo);
        lblInfo.setBounds(10, 10, 400, 20);

    btnRespaldo.setText("Generar respaldo");
        btnRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onGenerarRespaldo();
            }
        });
        jPanel1.add(btnRespaldo);
        btnRespaldo.setBounds(120, 50, 170, 30);

    btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onVolver();
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(120, 90, 170, 30);

    jProgressBar1.setIndeterminate(false);
    jPanel1.add(jProgressBar1);
    jProgressBar1.setBounds(30, 130, 360, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                         

    private void onGenerarRespaldo() {
        // Build a default filename on the user's Desktop
        String time = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        File defaultFile = new File(System.getProperty("user.home") + File.separator + "Desktop", "bmll_backup_" + time + ".sql");

        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Guardar respaldo");
        chooser.setSelectedFile(defaultFile);
        int sel = chooser.showSaveDialog(this);
        if (sel != javax.swing.JFileChooser.APPROVE_OPTION) {
            // User cancelled
            return;
        }

        File outFile = chooser.getSelectedFile();
    btnRespaldo.setEnabled(false);
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    jProgressBar1.setIndeterminate(true);

        new SwingWorker<File, Void>(){
            @Override
            protected File doInBackground() throws Exception {
                // Validate DB connection availability
                try (Connection c = conexionSQL.getConnection()) {
                    if (c == null) throw new SQLException("No se pudo establecer conexión con la base de datos");
                }

                // Perform JDBC-based dump: use SHOW CREATE TABLE and SELECT data to build INSERTs
                try (Connection conn = conexionSQL.getConnection(); FileOutputStream fos = new FileOutputStream(outFile)) {
                    if (conn == null) throw new SQLException("No se pudo establecer conexión con la base de datos");

                    String jdbcUrl = conexionSQL.getDbUrl();
                    // determine catalog/database from jdbc url
                    String database = null;
                    try {
                        String tmp = jdbcUrl;
                        if (tmp.startsWith("jdbc:")) tmp = tmp.substring(tmp.indexOf(":") + 1);
                        if (tmp.startsWith("//")) tmp = tmp.substring(2);
                        if (tmp.startsWith("mysql:")) tmp = tmp.substring("mysql:".length());
                        if (tmp.startsWith("//")) tmp = tmp.substring(2);
                        String[] parts = tmp.split("/", 2);
                        if (parts.length == 2) {
                            database = parts[1];
                            if (database.contains("?")) database = database.split("\\?",2)[0];
                        }
                    } catch (Exception ex) {
                        // ignore
                    }

                    String header = "-- BMLL SQL Backup\n-- Generated: " + new Date() + "\n\n";
                    fos.write(header.getBytes());
                    fos.write("SET FOREIGN_KEY_CHECKS=0;\n".getBytes());
                    fos.write("SET NAMES utf8mb4;\n\n".getBytes());

                    DatabaseMetaData meta = conn.getMetaData();
                    ResultSet tablesRs = meta.getTables(conn.getCatalog(), null, "%", new String[]{"TABLE"});
                    List<String> tables = new ArrayList<>();
                    while (tablesRs.next()) {
                        String tblCat = tablesRs.getString("TABLE_CAT");
                        String tblName = tablesRs.getString("TABLE_NAME");
                        // if database was detected, filter by catalog
                        if (database == null || database.isEmpty() || tblCat == null || tblCat.equals(database)) {
                            tables.add(tblName);
                        }
                    }
                    tablesRs.close();

                    Statement stmt = conn.createStatement();
                    for (String tbl : tables) {
                        // Write DROP + CREATE statement using SHOW CREATE TABLE for accurate DDL
                        try (ResultSet createRs = stmt.executeQuery("SHOW CREATE TABLE `" + tbl + "`")) {
                            if (createRs.next()) {
                                String createSql = createRs.getString(2);
                                fos.write(("-- ----------------------------\n").getBytes());
                                fos.write(("-- Table structure for `" + tbl + "`\n").getBytes());
                                fos.write(("-- ----------------------------\n").getBytes());
                                fos.write(("DROP TABLE IF EXISTS `" + tbl + "`;\n").getBytes());
                                fos.write((createSql + ";\n\n").getBytes());
                            }
                        }

                        // Dump table data
                        try (ResultSet rs = stmt.executeQuery("SELECT * FROM `" + tbl + "`")) {
                            ResultSetMetaData rsmd = rs.getMetaData();
                            int cols = rsmd.getColumnCount();
                            StringBuilder insertPrefix = new StringBuilder();
                            insertPrefix.append("INSERT INTO `").append(tbl).append("` (");
                            for (int i = 1; i <= cols; i++) {
                                insertPrefix.append("`").append(rsmd.getColumnName(i)).append("`");
                                if (i < cols) insertPrefix.append(",");
                            }
                            insertPrefix.append(") VALUES ");

                            boolean firstRowWritten = false;
                            StringBuilder batch = new StringBuilder();
                            while (rs.next()) {
                                StringBuilder values = new StringBuilder();
                                values.append("(");
                                for (int i = 1; i <= cols; i++) {
                                    Object obj = rs.getObject(i);
                                    if (obj == null) {
                                        values.append("NULL");
                                    } else {
                                        int type = rsmd.getColumnType(i);
                                        if (type == java.sql.Types.INTEGER || type == java.sql.Types.BIGINT || type == java.sql.Types.SMALLINT || type == java.sql.Types.TINYINT || type == java.sql.Types.NUMERIC || type == java.sql.Types.DECIMAL || type == java.sql.Types.FLOAT || type == java.sql.Types.DOUBLE) {
                                            values.append(obj.toString());
                                        } else {
                                            String s = rs.getString(i);
                                            if (s == null) {
                                                values.append("NULL");
                                            } else {
                                                // Handle MySQL "zero" dates like '0000-00-00' or '0000-00-00 00:00:00'
                                                boolean isDateType = (type == java.sql.Types.DATE || type == java.sql.Types.TIME || type == java.sql.Types.TIMESTAMP);
                                                if (isDateType) {
                                                    String trimmed = s.trim();
                                                    if (trimmed.startsWith("0000-00-00") || trimmed.startsWith("0000-00-00 00:00:00") || trimmed.equals("0000-00-00")) {
                                                        // Export as NULL to avoid "zero date" errors on import
                                                        values.append("NULL");
                                                        if (i < cols) { /* nothing */ }
                                                        // continue to next column
                                                        if (i < cols) { }
                                                        // skip escaping
                                                        // no further action
                                                    } else {
                                                        s = s.replace("\\", "\\\\");
                                                        s = s.replace("'", "\\'");
                                                        values.append("'").append(s).append("'");
                                                    }
                                                } else {
                                                    s = s.replace("\\", "\\\\");
                                                    s = s.replace("'", "\\'");
                                                    values.append("'").append(s).append("'");
                                                }
                                            }
                                        }
                                    }
                                    if (i < cols) values.append(",");
                                }
                                values.append(")");

                                if (!firstRowWritten) {
                                    batch.append(insertPrefix);
                                    batch.append(values);
                                    firstRowWritten = true;
                                } else {
                                    batch.append(",");
                                    batch.append(values);
                                }

                                // write batch periodically to avoid huge memory usage
                                if (batch.length() > 1_000_000) {
                                    batch.append(";\n");
                                    fos.write(batch.toString().getBytes());
                                    batch.setLength(0);
                                    firstRowWritten = false;
                                }
                            }

                            if (batch.length() > 0) {
                                batch.append(";\n\n");
                                fos.write(batch.toString().getBytes());
                                batch.setLength(0);
                            }
                        }
                    }

                    fos.write("SET FOREIGN_KEY_CHECKS=1;\n".getBytes());
                    stmt.close();
                }

                return outFile;
            }

            @Override
            protected void done() {
                jProgressBar1.setIndeterminate(false);
                setCursor(Cursor.getDefaultCursor());
                btnRespaldo.setEnabled(true);
                try {
                    File f = get();
                    JOptionPane.showMessageDialog(Ajustes.this, "Respaldo creado:\n" + f.getAbsolutePath(), "Respaldo completado", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(Ajustes.this, "Error al crear respaldo:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }

    private void onVolver() {
        // Reopen MenuPrincipal centered and close this window
        try {
            MenuPrincipal menu = new MenuPrincipal();
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
        } catch (Exception ex) {
            // If something goes wrong, show an error but still dispose
            JOptionPane.showMessageDialog(this, "No se pudo abrir el menú principal: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRespaldo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
