/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import DAO.CategoriaDAO;
import Modelo.Categorias;
import controlador.LogicaBotonActualizar;
import controlador.conexionSQL;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.util.List;
// image loading via ImageHelper
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luise
 */
public class BuscarCategoriaActualizar extends javax.swing.JFrame {
    private Connection con;
    // guarda la última categoria válida seleccionada para evitar borrar accidentalmente
    
    public BuscarCategoriaActualizar() {
        initComponents();
        CargarLogo();
        con = conexionSQL.getConnection();
        // crear y reutilizar una sola instancia del controlador para ahorrar recursos

        cargarCategorias();
        // registrar listener después de cargar categorias para evitar disparos en init
        // permitir que Enter en el campo de texto dispare el botón Buscar (mejora UX)
        box_titulo.addActionListener(evt -> btn_buscar.doClick());
        
        tb_consulta.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 16));
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        tb_consulta.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "volver");
        getRootPane().getActionMap().put("volver", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Reuse the generated action handler so behavior stays in one place
                btn_volverActionPerformed(new ActionEvent(BuscarCategoriaActualizar.this, ActionEvent.ACTION_PERFORMED, "escape"));
            }
        });
        
    }

  

    public BuscarCategoriaActualizar(String title) {
        this(); // inicializa todo
        // restaurar título si existe
        if (title != null && !title.trim().isEmpty()) {
            box_titulo.setText(title);
            cargarCategorias();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        lbl_curva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(1360, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Actualizar categoria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        tb_consulta.setBackground(new java.awt.Color(255, 255, 255));
        tb_consulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Acción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_consulta.setColumnSelectionAllowed(true);
        tb_consulta.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tb_consulta);
        tb_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1280, 570));

        box_titulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(box_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 660, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Nombre: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 210, -1));

        btn_buscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 113, 114));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 200, -1));

        btn_volver.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 50));

        lbl_curva.setText("jLabel3");
        jPanel1.add(lbl_curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1360, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCategorias(){
        
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión");
            return;
        }
        
        String Titulo = box_titulo.getText().trim();
        
        // usar la instancia del controlador creada en el constructor
        List lista = new ArrayList<>();

    StringBuilder sql = new StringBuilder(
        "SELECT id, nombre FROM categorias"
    ); // Cambio de la sentencia sql para incluir el codigo del estante con la fila

    // Buscar/filtrar por titulo y limita los resultados a 50
    
    if (Titulo != null && !Titulo.trim().isEmpty()) {
        sql.append(" WHERE nombre LIKE ?");
    } 

    try (PreparedStatement ps = con.prepareStatement(sql.toString())) {
        if (Titulo != null && !Titulo.trim().isEmpty()) {
            ps.setString(1, "%" + Titulo + "%");
        }

        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {    
                Categorias c = new Categorias(rs.getInt("id"), rs.getString("nombre"));
                lista.add(c);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
        actualizarTabla(lista);

    }
          

    private void CargarLogo(){
        lbl_curva.setIcon(ImageHelper.getScaledIcon("/archivos/luis4.png", lbl_curva.getWidth(), lbl_curva.getHeight()));
//        lbl_globo.setIcon(ImageHelper.getScaledIcon("/archivos/globo.png", lbl_globo.getWidth(), lbl_globo.getHeight()));
  //      lbl_libros.setIcon(ImageHelper.getScaledIcon("/archivos/Vizcalla2.png", lbl_libros.getWidth(), lbl_libros.getHeight()));
    }

    // getters para permitir que controladores externos lean el estado de búsqueda
    public String getCurrentSearchTitle() {
        return box_titulo.getText().trim();
    }

    // Unifica la actualización de la tabla (incluye configurar renderer/editor del botón)
    private void actualizarTabla(List<Categorias> libros) {
        DefaultTableModel modelo = (DefaultTableModel) tb_consulta.getModel();
        modelo.setRowCount(0);

        if (libros == null || libros.isEmpty()) {
            return;
        }

        for (Categorias l : libros) {
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNombre(),
                "Actualizar"
            });
        }

        // Ocultar columna id
        if (tb_consulta.getColumnModel().getColumnCount() > 0) {
            tb_consulta.getColumnModel().getColumn(0).setMinWidth(0);
            tb_consulta.getColumnModel().getColumn(0).setMaxWidth(0);
            tb_consulta.getColumnModel().getColumn(0).setWidth(0);
        }

        int colBoton = tb_consulta.getColumnCount() - 1;
        // Asignar renderer y editor para botón actualizar (reutiliza la instancia control)
        tb_consulta.getColumnModel().getColumn(colBoton).setCellRenderer(new RenderizarBotonActualizar());
        tb_consulta.getColumnModel().getColumn(colBoton).setCellEditor(new LogicaBotonActualizar(new JCheckBox(), tb_consulta, "categoria"));

        tb_consulta.setRowHeight(30);
    }
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        cargarCategorias();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarLibroActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_curva;
    private javax.swing.JTable tb_consulta;
    // End of variables declaration//GEN-END:variables

    public void open() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }
}
