/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import DAO.CategoriaDAO;
import Modelo.Categorias;
import Modelo.Libro;
import controlador.LogicaBotonActualizar;
import controlador.conexionSQL;
import controlador.controlLibro;
import java.awt.Font;
import java.sql.Connection;
import java.util.List;
// image loading via ImageHelper
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luise
 */
public class BuscarLibroActualizar extends javax.swing.JFrame {
    private Connection con;
    private controlador.controlLibro control;
    // guarda la última categoria válida seleccionada para evitar borrar accidentalmente
    private int lastSelectedCategoryId = -1;
    
    public BuscarLibroActualizar() {
        initComponents();
        CargarLogo();
        con = conexionSQL.getConnection();
        // crear y reutilizar una sola instancia del controlador para ahorrar recursos
        control = new controlador.controlLibro(con);

        cargarCategorias();
        // registrar listener después de cargar categorias para evitar disparos en init
        setupCategoriaListener();
        tb_consulta.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 16));
        // permitir que Enter en el campo de texto dispare el botón Buscar (mejora UX)
        box_titulo.addActionListener(evt -> btn_buscar.doClick());
        // Bind Escape to Volver button
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "volver");
        getRootPane().getActionMap().put("volver", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btn_volver.doClick();
            }
        });
        
    }

  

    public BuscarLibroActualizar(String title, int categoryId) {
        this(); // inicializa todo
        // restaurar título si existe
        if (title != null && !title.trim().isEmpty()) {
            box_titulo.setText(title);
            cargarLibros();
        }

        // si hay categoría válida, seleccionarla y cargar por categoría
        if (categoryId > 0) {
            // buscar el item en el combo y seleccionarlo
            for (int i = 0; i < combo_categorias.getItemCount(); i++) {
                Object item = combo_categorias.getItemAt(i);
                if (item instanceof Categorias) {
                    Categorias c = (Categorias) item;
                    if (c.getId() == categoryId) {
                        // establecer selección; listener cargará los libros por categoría
                        combo_categorias.setSelectedIndex(i);
                        lastSelectedCategoryId = categoryId;
                        break;
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        combo_categorias = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        lbl_curva = new javax.swing.JLabel();
        lbl_globo = new javax.swing.JLabel();
        lbl_libros = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 130, 37));
        jLabel1.setText("Actualizar Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        tb_consulta.setBackground(new java.awt.Color(255, 255, 255));
        tb_consulta.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Acción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_consulta.setColumnSelectionAllowed(true);
        tb_consulta.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tb_consulta);
        tb_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1280, 550));

        box_titulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(box_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 630, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 130, 37));
        jLabel2.setText("Titulo de libro: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 210, -1));

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 113, 114));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 120, -1));

        combo_categorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(combo_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 290, -1));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 50));
        jPanel1.add(lbl_curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1310, 510));
        jPanel1.add(lbl_globo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -30, 230, 220));
        jPanel1.add(lbl_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, 170, 100));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 130, 37));
        jLabel3.setText("Categorias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarLibros(){
        
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión");
        return;
        }
        
        String Titulo = box_titulo.getText().trim();
        
        // usar la instancia del controlador creada en el constructor
        List<Libro> libros = control.obtenerLibros(Titulo);
        actualizarTabla(libros);

    }
    
     private void cargarCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        try{
           // añadir opción por defecto que no debe disparar búsqueda
           combo_categorias.addItem(new Modelo.Categorias(-1, "Seleccione una categoria"));
           for(Categorias c : dao.ListarCategorias()){
              combo_categorias.addItem(c);
           } 
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Registra el ItemListener para el combo de categorías
    private void setupCategoriaListener() {
        combo_categorias.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    Object obj = e.getItem();
                    if (obj instanceof Categorias) {
                        Categorias c = (Categorias) obj;
                        int newId = c.getId();
                        // si es placeholder o la misma categoría que ya estaba seleccionada, no hacer nada
                        if (newId <= 0 || newId == lastSelectedCategoryId) {
                            return;
                        }
                        // nueva selección válida: limpiar el campo y cargar
                        box_titulo.setText("");
                        cargarLibrosPorCategoria();
                        lastSelectedCategoryId = newId;
                    }
                }
            }
        });
    }

    private void cargarLibrosPorCategoria(){
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión");
        return;
        }

        Categorias cat = (Categorias) combo_categorias.getSelectedItem();
        if (cat == null || cat.getId() <= 0) return;

        List<Libro> libros = control.obtenerLibrosPorCategoria(cat.getId());
        actualizarTabla(libros);
    }

          

    private void CargarLogo(){
        lbl_curva.setIcon(ImageHelper.getScaledIcon("/archivos/luis4.png", lbl_curva.getWidth(), lbl_curva.getHeight()));
        lbl_globo.setIcon(ImageHelper.getScaledIcon("/archivos/globo.png", lbl_globo.getWidth(), lbl_globo.getHeight()));
        lbl_libros.setIcon(ImageHelper.getScaledIcon("/archivos/Vizcalla3.png", lbl_libros.getWidth(), lbl_libros.getHeight()));
    }

    // getters para permitir que controladores externos lean el estado de búsqueda
    public String getCurrentSearchTitle() {
        return box_titulo.getText().trim();
    }

    public int getCurrentSelectedCategoryId() {
        Object sel = combo_categorias.getSelectedItem();
        if (sel instanceof Categorias) return ((Categorias) sel).getId();
        return -1;
    }

    // Unifica la actualización de la tabla (incluye configurar renderer/editor del botón)
    private void actualizarTabla(List<Libro> libros) {
        DefaultTableModel modelo = (DefaultTableModel) tb_consulta.getModel();
        // keep the designer's column order (Titulo, Autor, Acción) and don't change identifiers here
        modelo.setRowCount(0);

        if (libros == null || libros.isEmpty()) {
            // clear any stored ids
            tb_consulta.putClientProperty("rowIds", new java.util.ArrayList<Integer>());
            return;
        }

        java.util.List<Integer> rowIds = new java.util.ArrayList<>();

        for (Libro l : libros) {
            modelo.addRow(new Object[]{
                l.getTitulo(),
                l.getAutor(),
                "Actualizar"
            });
            rowIds.add(l.getId());
        }

        // store ids so editors can find the real id without modifying visible columns
        tb_consulta.putClientProperty("rowIds", rowIds);

        int colBoton = tb_consulta.getColumnCount() - 1;
        // Asignar renderer y editor para botón actualizar (reutiliza la instancia control)
        tb_consulta.getColumnModel().getColumn(colBoton).setCellRenderer(new RenderizarBotonActualizar());
        tb_consulta.getColumnModel().getColumn(colBoton).setCellEditor(new LogicaBotonActualizar(new JCheckBox(), tb_consulta, control));

        tb_consulta.setRowHeight(30);
    }
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        cargarLibros();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarLibroActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarLibroActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<Categorias> combo_categorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_curva;
    private javax.swing.JLabel lbl_globo;
    private javax.swing.JLabel lbl_libros;
    private javax.swing.JTable tb_consulta;
    // End of variables declaration//GEN-END:variables

    public void open() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }
}
