
package Vista;

import DAO.CategoriaDAO;
import Modelo.Categorias;
import Modelo.Libro;
import controlador.conexionSQL;
import controlador.controlLibro;
import java.awt.Image;
import java.sql.Connection;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luise
 */
public class Consultas extends javax.swing.JFrame {
    private Connection con;
    
    public Consultas() {
        initComponents();
        con = conexionSQL.getConnection();
        cargarCategorias();
        CargarLogo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_consulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        combo_categorias = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        lbl_libros = new javax.swing.JLabel();
        lbl_lupa = new javax.swing.JLabel();
        lbl_curva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_consulta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_consulta.setForeground(new java.awt.Color(242, 130, 37));
        lbl_consulta.setText("Consulta Libros");
        jPanel1.add(lbl_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 15, -1, -1));

        tb_consulta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tb_consulta.setForeground(new java.awt.Color(0, 113, 114));
        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Tomo", "Cantidad", "Posicion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_consulta.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb_consulta);
        tb_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 111, 866, -1));
        jPanel1.add(box_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 69, 420, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(242, 130, 37));
        lbl_titulo.setText("Titulo de libro: ");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 65, -1, -1));

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 113, 114));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 66, 104, -1));

        combo_categorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo_categorias.setForeground(new java.awt.Color(0, 113, 114));
        jPanel1.add(combo_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 66, 172, -1));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, -1, -1));

        lbl_libros.setText("jLabel3");
        jPanel1.add(lbl_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -40, 220, 210));

        lbl_lupa.setText("jLabel3");
        jPanel1.add(lbl_lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -10, 180, 170));

        lbl_curva.setText("jLabel3");
        jPanel1.add(lbl_curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 940, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CargarLogo(){
         
        ImageIcon icn = new ImageIcon(getClass().getResource("/archivos/luis4.png"));
        Image in = icn.getImage().getScaledInstance(lbl_curva.getWidth(),lbl_curva.getHeight(), Image.SCALE_SMOOTH);
        lbl_curva.setIcon(new ImageIcon(in));
        
        
        ImageIcon icw = new ImageIcon(getClass().getResource("/archivos/Vizcalla3.png"));
        Image iw = icw.getImage().getScaledInstance(lbl_libros.getWidth(),lbl_libros.getHeight(), Image.SCALE_SMOOTH);
        lbl_libros.setIcon(new ImageIcon(iw));
        
        ImageIcon icc = new ImageIcon(getClass().getResource("/archivos/lupa.png"));
        Image ic = icc.getImage().getScaledInstance(lbl_lupa.getWidth(),lbl_lupa.getHeight(), Image.SCALE_SMOOTH);
        lbl_lupa.setIcon(new ImageIcon(ic));
    }
    
    private void cargarLibros(){
        
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión");
        return;
        }
        
        String Titulo = box_titulo.getText().trim();
        
        DefaultTableModel modelo = (DefaultTableModel) tb_consulta.getModel();
        modelo.setRowCount(0);
        
        controlLibro control = new controlLibro(con);
        List<Libro> libros = control.obtenerLibros(Titulo);
        
       for (Libro l : libros) {
        modelo.addRow(new Object[]{
            l.getTitulo(),
            l.getAutor(),
            l.getTomo(),
            l.getN_copias(),
            l.getPosicion(),
        });
        }
    }
    
    private void cargarCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        try{
           for(Categorias c : dao.ListarCategorias()){
              combo_categorias.addItem(c);
           } 
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:

        cargarLibros();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<Categorias> combo_categorias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_consulta;
    private javax.swing.JLabel lbl_curva;
    private javax.swing.JLabel lbl_libros;
    private javax.swing.JLabel lbl_lupa;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTable tb_consulta;
    // End of variables declaration//GEN-END:variables

    public void open() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }
}
