
package Vista;

import DAO.CategoriaDAO;
import Modelo.Categorias;
import Modelo.Libro;
import controlador.conexionSQL;
import controlador.controlLibro;
import java.sql.Connection;
import java.util.List;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luise
 */
public class Consultas extends javax.swing.JFrame {
    private Connection con;
    private controlador.controlLibro control;
    // guarda la última categoria válida seleccionada para evitar borrar accidentalmente el campo de título
    private int lastSelectedCategoryId = -1;
    
    public Consultas() {
        initComponents();
        con = conexionSQL.getConnection();
        // crear y reutilizar una sola instancia del controlador para ahorrar recursos
        control = new controlador.controlLibro(con);

        cargarCategorias();

        // registrar el listener desde un método separado para mantener el constructor limpio
        // (se registra después de cargar las categorías para evitar disparos en la inicialización)
        setupCategoriaListener();
        // permitir que Enter en el campo de texto dispare el botón Buscar (mejora UX)
        box_titulo.addActionListener(evt -> btn_buscar.doClick());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_consulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        combo_categorias = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_consulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_consulta.setForeground(new java.awt.Color(0, 0, 0));
        lbl_consulta.setText("Consulta Libros");

        tb_consulta.setBackground(new java.awt.Color(255, 255, 255));
        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Tomo", "Cantidad", "Posicion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_consulta.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb_consulta);
        tb_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setText("Titulo de libro: ");

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        combo_categorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_volver)
                        .addGap(308, 308, 308)
                        .addComponent(lbl_consulta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_titulo)
                                .addGap(18, 18, 18)
                                .addComponent(box_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_consulta)
                    .addComponent(btn_volver))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo)
                    .addComponent(btn_buscar)
                    .addComponent(combo_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarLibros(){
        
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión");
        return;
        }
        
        String Titulo = box_titulo.getText().trim();
        
        List<Libro> libros = control.obtenerLibros(Titulo);
        actualizarTabla(libros);
    }
    
    private void cargarCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        try{
           // añadir opción por defecto que no debe disparar búsqueda
           combo_categorias.addItem(new Modelo.Categorias(-1, "Seleccione una categoria"));
           for(Categorias c : dao.ListarCategorias()){
              combo_categorias.addItem(c);
           } 
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Registro del ItemListener en un método separado para mantener el constructor limpio
    private void setupCategoriaListener() {
        combo_categorias.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    Object obj = e.getItem();
                    if (obj instanceof Categorias) {
                        Categorias c = (Categorias) obj;
                        int newId = c.getId();
                        // si es placeholder o la misma categoría que ya estaba seleccionada, no hacer nada
                        if (newId <= 0 || newId == lastSelectedCategoryId) {
                            return;
                        }
                        // nueva selección válida: limpiar el campo y cargar
                        box_titulo.setText("");
                        cargarLibrosPorCategoria();
                        lastSelectedCategoryId = newId;
                    }
                }
            }
        });
    }

    private void cargarLibrosPorCategoria(){
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión");
            return;
        }

        Categorias cat = (Categorias) combo_categorias.getSelectedItem();
        // si es la opción por defecto, no hacer nada
        if (cat == null || cat.getId() <= 0) return;

        List<Libro> libros = control.obtenerLibrosPorCategoria(cat.getId());
        actualizarTabla(libros);
    }

    // Actualiza la tabla a partir de una lista de libros (null/empty check dentro)
    private void actualizarTabla(List<Libro> libros) {
        DefaultTableModel modelo = (DefaultTableModel) tb_consulta.getModel();
        modelo.setRowCount(0);

        if (libros == null || libros.isEmpty()) {
            return;
        }

        for (Libro l : libros) {
            modelo.addRow(new Object[]{
                l.getTitulo(),
                l.getAutor(),
                l.getTomo(),
                l.getN_copias(),
                l.getPosicion(),
            });
        }
    }
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:

        cargarLibros();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<Categorias> combo_categorias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_consulta;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTable tb_consulta;
    // End of variables declaration//GEN-END:variables

    public void open() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }

    /**
     * Permite habilitar/deshabilitar el botón "Volver" desde código externo.
     * Útil para usuarios sin permisos de navegación completa.
     */
    public void setVolverEnabled(boolean enabled) {
        btn_volver.setEnabled(enabled);
    }
}
