
package Vista;

import DAO.CategoriaDAO;
import Modelo.Categorias;
import Modelo.Libro;
import controlador.conexionSQL;
import controlador.controlLibro;
import java.sql.Connection;
import java.util.List;
// image loading via ImageHelper
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
// image loading via ImageHelper
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luise
 */
public class Consultas extends javax.swing.JFrame {
    private Connection con;
    private controlador.controlLibro control;
    // guarda la última categoria válida seleccionada para evitar borrar accidentalmente el campo de título
    private int lastSelectedCategoryId = -1;
    
    public Consultas() {
        initComponents();
        CargarLogo();
        con = conexionSQL.getConnection();
        // crear y reutilizar una sola instancia del controlador para ahorrar recursos
        control = new controlador.controlLibro(con);

        cargarCategorias();
    cargarEditoriales();

        // registrar el listener desde un método separado para mantener el constructor limpio
        // (se registra después de cargar las categorías para evitar disparos en la inicialización)
        setupCategoriaListener();
        // permitir que Enter en el campo de texto dispare el botón Buscar (mejora UX)
        box_titulo.addActionListener(evt -> btn_buscar.doClick());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_consulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        combo_categorias = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();
        lbl_curva = new javax.swing.JLabel();
        lbl_libros = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_categoria = new javax.swing.JLabel();
        lbl_editorial = new javax.swing.JLabel();
        lbl_lupa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 226, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_consulta.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_consulta.setForeground(new java.awt.Color(242, 130, 37));
        lbl_consulta.setText("Consulta Libros");
        jPanel1.add(lbl_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        tb_consulta.setBackground(new java.awt.Color(255, 255, 255));
        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Tomo", "Cantidad", "Posicion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_consulta.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb_consulta);
        tb_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 161, 1280, 520));

        box_titulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(box_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 510, 30));

        lbl_titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(242, 130, 37));
        lbl_titulo.setText("Titulo de libro");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        btn_buscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 113, 114));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 140, 30));

        combo_categorias.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(combo_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 250, 30));

        btn_volver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));
        jPanel1.add(lbl_curva, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 320, 1360, 400));
        jPanel1.add(lbl_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 210, 140));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 330, 30));

        lbl_categoria.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbl_categoria.setForeground(new java.awt.Color(242, 130, 37));
        lbl_categoria.setText("Categorias");
        jPanel1.add(lbl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        lbl_editorial.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbl_editorial.setForeground(new java.awt.Color(242, 130, 37));
        lbl_editorial.setText("Editoriales");
        jPanel1.add(lbl_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, -1, -1));
        jPanel1.add(lbl_lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, -10, 210, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarLibros(){
        
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión");
        return;
        }
        
        String Titulo = box_titulo.getText().trim();
        
        List<Libro> libros = control.obtenerLibros(Titulo);
        actualizarTabla(libros);
    }
    
    private void cargarCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        try{
           // añadir opción por defecto que no debe disparar búsqueda
           combo_categorias.addItem(new Modelo.Categorias(-1, "Seleccione una categoria"));
           for(Categorias c : dao.ListarCategorias()){
              combo_categorias.addItem(c);
           } 
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void cargarEditoriales(){
        try{
            List<String> editoriales = control.listarEditoriales();
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Seleccione una editorial");
            if(editoriales != null){
                for(String ed : editoriales){
                    model.addElement(ed);
                }
            }
            jComboBox1.setModel(model);

            // listener para filtrar por editorial
            jComboBox1.addItemListener(new ItemListener(){
                @Override
                public void itemStateChanged(ItemEvent e){
                    if(e.getStateChange() == ItemEvent.SELECTED){
                        Object o = e.getItem();
                        if(o instanceof String){
                            String sel = (String) o;
                            if(sel == null || sel.equals("Seleccione una editorial")) return;
                            // limpiar búsqueda por título
                            box_titulo.setText("");
                            cargarLibrosPorEditorial(sel);
                        }
                    }
                }
            });
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    private void cargarLibrosPorEditorial(String editorial){
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión");
            return;
        }
        List<Libro> libros = control.obtenerLibrosPorEditorial(editorial);
        actualizarTabla(libros);
    }

    // Registro del ItemListener en un método separado para mantener el constructor limpio
    private void setupCategoriaListener() {
        combo_categorias.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    Object obj = e.getItem();
                    if (obj instanceof Categorias) {
                        Categorias c = (Categorias) obj;
                        int newId = c.getId();
                        // si es placeholder o la misma categoría que ya estaba seleccionada, no hacer nada
                        if (newId <= 0 || newId == lastSelectedCategoryId) {
                            return;
                        }
                        // nueva selección válida: limpiar el campo y cargar
                        box_titulo.setText("");
                        cargarLibrosPorCategoria();
                        lastSelectedCategoryId = newId;
                    }
                }
            }
        });
    }

    private void cargarLibrosPorCategoria(){
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión");
            return;
        }

        Categorias cat = (Categorias) combo_categorias.getSelectedItem();
        // si es la opción por defecto, no hacer nada
        if (cat == null || cat.getId() <= 0) return;

        List<Libro> libros = control.obtenerLibrosPorCategoria(cat.getId());
        actualizarTabla(libros);
    }

    // Actualiza la tabla a partir de una lista de libros (null/empty check dentro)
    private void actualizarTabla(List<Libro> libros) {
        DefaultTableModel modelo = (DefaultTableModel) tb_consulta.getModel();
        modelo.setRowCount(0);

        if (libros == null || libros.isEmpty()) {
            return;
        }

        for (Libro l : libros) {
            modelo.addRow(new Object[]{
                l.getTitulo(),
                l.getAutor(),
                l.getTomo(),
                l.getN_copias(),
                l.getPosicion(),
            });
        }
    }
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:

        cargarLibros();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<Categorias> combo_categorias;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_consulta;
    private javax.swing.JLabel lbl_curva;
    private javax.swing.JLabel lbl_editorial;
    private javax.swing.JLabel lbl_libros;
    private javax.swing.JLabel lbl_lupa;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTable tb_consulta;
    // End of variables declaration//GEN-END:variables

    private void CargarLogo(){
        lbl_curva.setIcon(ImageHelper.getScaledIcon("/archivos/luis4.png", lbl_curva.getWidth(), lbl_curva.getHeight()));
        lbl_libros.setIcon(ImageHelper.getScaledIcon("/archivos/Vizcalla3.png", lbl_libros.getWidth(), lbl_libros.getHeight()));
        lbl_lupa.setIcon(ImageHelper.getScaledIcon("/archivos/lupa.png", lbl_lupa.getWidth(), lbl_lupa.getHeight()));
    }

    public void open() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }

 
    public void setVolverEnabled(boolean enabled) {
        btn_volver.setEnabled(enabled);
    }
}
