/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import controlador.conexionSQL;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author DELL
 */
public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EliminarUsuario
     */
    public EditarUsuario() {
        initComponents();
        cargarUsuarios();
        
        // Bind Escape key to call the same handler as the Volver button.
        // The NetBeans-generated code declares the button as a local variable inside initComponents(),
        // so we invoke the existing action method directly instead of calling doClick() on the button instance.
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "volver");
        getRootPane().getActionMap().put("volver", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Reuse the generated action handler so behavior stays in one place
                btn_volverActionPerformed(new ActionEvent(EditarUsuario.this, ActionEvent.ACTION_PERFORMED, "escape"));
            }
        });
        
    }
    private void cargarUsuarios() {
        try {
            Connection con = controlador.conexionSQL.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id, usuario, is_admin FROM usuarios");

            ComboUsuarios.removeAllItems();

            while (rs.next()) {
                int id = rs.getInt("id");
                String usuario = rs.getString("usuario");
                int admin = rs.getInt("is_admin");

                String permiso = (admin == 1) ? "Administrador" : "Normal";

                ComboUsuarios.addItem(id + " - " + usuario + " - " + permiso);
            }

            rs.close();
            st.close();
            con.close();
            
            cargarRoles();
            cargarDatosUsuario();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        }
    }
    
    private void cargarRoles() {
        ComboRoles.removeAllItems();

        ComboRoles.addItem("Normal");
        ComboRoles.addItem("Administrador");
    }

private void cargarDatosUsuario() {
    try {
        if (ComboUsuarios.getSelectedItem() == null) return;

        String seleccionado = ComboUsuarios.getSelectedItem().toString();
        int id = Integer.parseInt(seleccionado.split(" - ")[0]);

        Connection con = controlador.conexionSQL.getConnection();
        PreparedStatement ps = con.prepareStatement(
            "SELECT nombre, apellido, cedula, usuario, password, is_admin FROM usuarios WHERE id = ?"
        );
        ps.setInt(1, id);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int admin = rs.getInt("is_admin");
            
            jtfNombre.setText(rs.getString("nombre"));
            jtfApellido.setText(rs.getString("apellido"));
            jtfCedula.setText(rs.getString("cedula"));
            jtfUsuario.setText(rs.getString("usuario"));
            jtfContraseña.setText(rs.getString("password"));
            
            if (admin == 1) {
                ComboRoles.setSelectedIndex(1); // Administrador
            } else {
                ComboRoles.setSelectedIndex(0); // Normal
            }
        }

        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        ComboUsuarios = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        LblApellido = new javax.swing.JLabel();
        Btn_Editar = new javax.swing.JButton();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfCedula = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        btn_volver = new javax.swing.JButton();
        lblCedula1 = new javax.swing.JLabel();
        jtfContraseña = new javax.swing.JTextField();
        lblCedula2 = new javax.swing.JLabel();
        ComboRoles = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(244, 226, 222));
        jPanel5.setForeground(new java.awt.Color(244, 226, 222));
        jPanel5.setMinimumSize(new java.awt.Dimension(1190, 700));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 45)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 130, 37));
        jLabel5.setText("Editar Usuario");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        lbl_Nombre.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(242, 130, 37));
        lbl_Nombre.setText("Nombre");
        jPanel5.add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(242, 130, 37));
        lblCedula.setText("Cedula");
        jPanel5.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        ComboUsuarios.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ComboUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        ComboUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Normal" }));
        ComboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuariosActionPerformed(evt);
            }
        });
        jPanel5.add(ComboUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 370, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 130, 37));
        jLabel8.setText("Elegir Usuario");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 190, -1));

        LblApellido.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        LblApellido.setForeground(new java.awt.Color(242, 130, 37));
        LblApellido.setText("Apellido");
        jPanel5.add(LblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, 30));

        Btn_Editar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Btn_Editar.setForeground(new java.awt.Color(0, 113, 114));
        Btn_Editar.setText("Editar");
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });
        jPanel5.add(Btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 260, 40));

        jtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jPanel5.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 380, -1));

        jtfApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 380, -1));

        jtfCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtfCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 380, -1));

        jtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel5.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 380, -1));

        btn_volver.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(0, 113, 114));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel5.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 260, 40));

        lblCedula1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblCedula1.setForeground(new java.awt.Color(242, 130, 37));
        lblCedula1.setText("Contraseña");
        jPanel5.add(lblCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        jtfContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 320, -1));

        lblCedula2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblCedula2.setForeground(new java.awt.Color(242, 130, 37));
        lblCedula2.setText("Permisos");
        jPanel5.add(lblCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        ComboRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRolesActionPerformed(evt);
            }
        });
        jPanel5.add(ComboRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 320, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 130, 37));
        jLabel9.setText("Usuario");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
        // TODO add your handling code here:                                             

    if (ComboUsuarios.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "No hay usuarios para editar.");
        return;
    }

    String seleccionado = ComboUsuarios.getSelectedItem().toString();
    int id = Integer.parseInt(seleccionado.split(" - ")[0]);

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Seguro que deseas editar este usuario?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        Connection con = controlador.conexionSQL.getConnection();
        PreparedStatement ps = con.prepareStatement("UPDATE usuarios SET nombre=?, apellido=?, cedula=?, usuario=?, password=?, is_admin=? WHERE id = ?");
        ps.setString(1, jtfNombre.getText());
        ps.setString(2, jtfApellido.getText());
        ps.setString(3, jtfCedula.getText());
        ps.setString(4, jtfUsuario.getText());
        ps.setString(5, jtfContraseña.getText());
        ps.setInt(6, ComboRoles.getSelectedIndex());
        ps.setInt(7, id);

        ps.executeUpdate();
        ps.close();
        con.close();

        JOptionPane.showMessageDialog(this, "Usuario editado exitosamente");

        // Recargar lista
        cargarUsuarios();

        // Limpiar campos
        jtfNombre.setText("");
        jtfApellido.setText("");
        jtfCedula.setText("");
        jtfUsuario.setText("");
        jtfContraseña.setText("");
        ComboRoles.setSelectedIndex(0);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + e.getMessage());
    }



        
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:

        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void ComboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUsuariosActionPerformed

    private void ComboRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRolesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboRolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Editar;
    private javax.swing.JComboBox<String> ComboRoles;
    private javax.swing.JComboBox<String> ComboUsuarios;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCedula;
    private javax.swing.JTextField jtfContraseña;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lbl_Nombre;
    // End of variables declaration//GEN-END:variables
}
