

// HAY QUE HACERLE UN POPUP PARA CONFIRMAR ELIMINACION, YA QUE VOY A SE VA A SELECCIONAR AL TOCAR EL LIBRO


package Vista;

import Modelo.Libro;
import controlador.conexionSQL;
import controlador.controlLibro;
import controlador.logicaBoton;
import static java.awt.SystemColor.control;
import java.util.List;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.JCheckBox;
/**
 *
 * @author luise
 */
public class EliminarLibro extends javax.swing.JFrame {
    private Connection con;
    private controlador.controlLibro control;
    // guarda la última categoria válida seleccionada para evitar borrar accidentalmente
    private int lastSelectedCategoryId = -1;
    
    public EliminarLibro() {
        initComponents();
        con = conexionSQL.getConnection();
        // crear y reutilizar una sola instancia del controlador
        control = new controlLibro(con);
        cargarCategorias();
        // registrar listener después de cargar categorias para evitar disparos en init
        setupCategoriaListener();
        // permitir que Enter en el campo de texto dispare el botón Buscar (mejora UX)
        box_titulo.addActionListener(evt -> btn_buscar.doClick());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        box_titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Eliminar Libros");

        tb_consulta.setBackground(new java.awt.Color(255, 255, 255));
        tb_consulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "autor", "tomo", "cantidad", "posicion", "accion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_consulta.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb_consulta);
        tb_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Titulo de libro: ");

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

    jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<Modelo.Categorias>());

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(box_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_volver)
                .addGap(308, 308, 308)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_volver))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_buscar)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarLibros(){
        
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión");
        return;
        }
        
        String Titulo = box_titulo.getText().trim();
        
        // usar la instancia compartida del controlador
        List<Libro> libros = control.obtenerLibros(Titulo);
        actualizarTablaEliminar(libros);
    }

    private void cargarCategorias(){
        DAO.CategoriaDAO dao = new DAO.CategoriaDAO();
        try{
            // opción por defecto
            jComboBox1.addItem(new Modelo.Categorias(-1, "Seleccione una categoria"));
            for(Modelo.Categorias c : dao.ListarCategorias()){
                jComboBox1.addItem(c);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void setupCategoriaListener() {
        jComboBox1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    Object obj = e.getItem();
                    if (obj instanceof Modelo.Categorias) {
                        Modelo.Categorias c = (Modelo.Categorias) obj;
                        int newId = c.getId();
                        if (newId <= 0 || newId == lastSelectedCategoryId) return;
                        box_titulo.setText("");
                        cargarLibrosPorCategoria();
                        lastSelectedCategoryId = newId;
                    }
                }
            }
        });
    }

    private void cargarLibrosPorCategoria(){
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión");
            return;
        }

        Modelo.Categorias cat = (Modelo.Categorias) jComboBox1.getSelectedItem();
        if (cat == null || cat.getId() <= 0) return;

        List<Libro> libros = control.obtenerLibrosPorCategoria(cat.getId());
        actualizarTablaEliminar(libros);
    }

    private void actualizarTablaEliminar(List<Libro> libros) {
        DefaultTableModel modelo = (DefaultTableModel) tb_consulta.getModel();
        modelo.setRowCount(0);
        if (libros == null || libros.isEmpty()) return;

        for (Libro l : libros) {
            modelo.addRow(new Object[]{
                l.getId(),
                l.getTitulo(),
                l.getAutor(),
                l.getTomo(),
                l.getN_copias(),
                l.getPosicion(),
                "eliminar"
            });
        }

        // oculta la columna id para pasarla al boton eliminar (si existe)
        if (tb_consulta.getColumnModel().getColumnCount() > 0) {
            try {
                tb_consulta.getColumnModel().getColumn(0).setMinWidth(0);
                tb_consulta.getColumnModel().getColumn(0).setMaxWidth(0);
                tb_consulta.getColumnModel().getColumn(0).setWidth(0);
            } catch (Exception ex) {
                // defensivo: si algo cambia en el modelo de columnas, evitamos crash
                System.err.println("Advertencia al ocultar columna id: " + ex.getMessage());
            }
        }

        // calcular índice de la columna del botón dinámicamente (última columna en el modelo)
        int colBoton = modelo.getColumnCount() - 1;

        // registrar renderer/editor sólo si la columna existe en el TableColumnModel
        int visibleColumns = tb_consulta.getColumnModel().getColumnCount();
        if (colBoton >= 0 && colBoton < visibleColumns) {
            try {
                tb_consulta.getColumnModel().getColumn(colBoton).setCellEditor(
                    new logicaBoton(new JCheckBox(), tb_consulta, control, () -> {
                        // limpiar cuadro de búsqueda
                        box_titulo.setText("");
                        // resetear combo a opción placeholder si existe
                        if (jComboBox1.getItemCount() > 0) jComboBox1.setSelectedIndex(0);
                        // resetear lastSelectedCategoryId para permitir re-selección
                        lastSelectedCategoryId = -1;
                    })
                );
                tb_consulta.getColumnModel().getColumn(colBoton).setCellRenderer(new Renderizarboton());
            } catch (Exception ex) {
                System.err.println("No se pudo registrar editor/renderer en colBoton: " + ex.getMessage());
            }
        } else {
            // fallback: columna botón no encontrada (evita excepciones en tiempo de ejecución)
            System.err.println("Columna de acción no encontrada: colBoton=" + colBoton + " visibleColumns=" + visibleColumns);
        }

        tb_consulta.setRowHeight(30);
    }
    
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
   
        cargarLibros();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<Modelo.Categorias> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_consulta;
    // End of variables declaration//GEN-END:variables

    public void open() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }
}
